name = "fpmWENO"
version = "0.1.0"
license = "license"
author = "Jane Doe"
maintainer = "zahid3325@outlook.com"
copyright = "Copyright 2024, Jane Doe"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = true
source-form = "free"

